# One-off generator: build land.js (Skåne + Blekinge land outline) from Natural Earth admin-1.
# Source: https://github.com/nvkelso/natural-earth-vector (public domain)
import json, sys

SRC = r"C:\Users\Slyme\AppData\Local\Temp\ne10.geojson"
OUT = r"D:\weather-map-skane\land.js"
WANTED = {"Skåne", "Blekinge"}

def dp(points, tol):
    """Douglas-Peucker on an OPEN polyline; keeps first and last."""
    if len(points) < 3:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = points[a]
        bx, by = points[b]
        dx, dy = bx - ax, by - ay
        denom = (dx * dx + dy * dy) ** 0.5 or 1e-12
        dmax, imax = -1.0, -1
        for i in range(a + 1, b):
            px, py = points[i]
            dist = abs(dy * px - dx * py + bx * ay - by * ax) / denom
            if dist > dmax:
                dmax, imax = dist, i
        if dmax > tol:
            keep[imax] = True
            stack.append((a, imax))
            stack.append((imax, b))
    return [p for p, k in zip(points, keep) if k]

def dp_ring(ring, tol):
    """DP for a CLOSED ring (first == last): split at the farthest point from
    the start, simplify each half, rejoin — avoids a zero-length baseline."""
    pts = ring[:-1] if ring[0] == ring[-1] else ring[:]
    x0, y0 = pts[0]
    far = max(range(len(pts)), key=lambda i: (pts[i][0] - x0) ** 2 + (pts[i][1] - y0) ** 2)
    half1 = pts[:far + 1]
    half2 = pts[far:] + [pts[0]]
    out = dp(half1, tol)[:-1] + dp(half2, tol)[:-1]
    out.append(out[0])
    return out

def main():
    data = json.load(open(SRC, encoding="utf-8"))
    rings = []
    for f in data["features"]:
        p = f["properties"]
        if p.get("admin") == "Sweden" and p.get("name") in WANTED:
            geom = f["geometry"]
            polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
            for poly in polys:
                rings.append(poly[0])  # exterior ring only

    if not rings:
        sys.exit("no matching features found")
    print("input rings:", [len(r) for r in rings])

    # simplify: smallest tolerance in the list whose total stays under ~1600 points
    simplified = None
    for tol in (0.0003, 0.0006, 0.001, 0.0015, 0.002, 0.003):
        simplified = [dp_ring(r, tol) for r in rings]
        total = sum(len(r) for r in simplified)
        print(f"tol={tol}: {total} points")
        if total <= 1600:
            break

    out_rings = []
    for r in simplified:
        if len(r) < 4:
            continue
        out_rings.append([[round(lo, 4), round(la, 4)] for lo, la in r])

    total = sum(len(r) for r in out_rings)
    lons = [lo for r in out_rings for lo, _ in r]
    lats = [la for r in out_rings for _, la in r]
    print(f"rings={len(out_rings)} total_points={total}")
    print(f"bbox lat {min(lats)}..{max(lats)}  lon {min(lons)}..{max(lons)}")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("/* Skåne & Blekinge land outline — exterior rings as [lon, lat] pairs.\n")
        fh.write("   Source: Natural Earth admin-1 (public domain), simplified. Generated by tools/make_land_js.py */\n")
        fh.write("const LAND_RINGS = ")
        json.dump(out_rings, fh, separators=(",", ":"))
        fh.write(";\n")
    print("wrote", OUT)

if __name__ == "__main__":
    main()
